### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by nunojesus** [dilawar/HippoIgnited#1]
Hi, look to this logos I already prepair the png and svg of all, can I make the PR?

![all logos](https://user-images.githubusercontent.com/34600369/41510338-ab09740c-725a-11e8-815c-48afac7ec244.png)

**Comment by dilawar** [comment]
Dear Nuno

Looks great. Please submit a PR.

⁣Sent from Blue ​

**Comment by dilawar** [comment]
Please put them in data directory.

**Comment by nunojesus** [comment]
I create a PR with the logos files and I put the logo on the readme file and it looks really good.

It was a pleasure to work with you, if you need me Im here to help. 

If you have other projects to work I will be happy to help.

Greetings!

**Comment by dilawar** [comment]
Thank you @nunojesus . I've merged the PR. The logo should be online this weekend on the project site.

**Comment by nunojesus** [comment]
Great!

**Comment by dilawar** [comment]
The logo is now live.
